language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: mdDHxgznMOGKxiJXD2bmGJbzftf9v5tbJus6rznvN4Mf7TNhWlmiox3q7mgHp6e8401UryXpvIIVqsJ2ifCYTWxVckaBmfac9qg278y+UqNLY1U2RlMLwaubW1nrL1h3O3gUz6+wbSwTfBl5CIIPknPfXuzRVxKhyevjrTC2E7LehgWNCWkqr51udWCzBd11u1XXKnWs07VvzgnsqnDGc2HF9NxVrlKuFf1Sk8rNqLuhRHYqM0fq4j0GoEhwffshYAZXIUO9qbRe5R2ZnK/VuH4gfzTzvGpz7BFzRv+Qq5QVy0xCsjWNMzVRxB+gq0CNToIfmYZMR4at6hFpKoHXepfuN6BPUETZjG1DaK9vUOyxQ/gzQOToacWAlTLWhOOUWNrd/A3ZeTWMmE1ud09BmYbgbI3FLAks4Z6yRCRWkheE/Rf1ywxuUQw4laTeZAkxML8BLlYPCg0UWFhI0SGwQGI7EUZkNRk63N2XtHO6OoELTPCiMF3gzVrdDX9+KgxvRXBhQsGGy/prLmFJHIpeI/cTxD7G5Uf/dUwdte4XALS01o34FVz/oKUB/KMDXgIGxDF30lEqjv91nDUaOQ56s8/y+wa3V9aS2l8gl3Ox/bkIxEeQgBPIzM4AKtNLxU3pPYRZ2uKpRfq0DSwxJ4pQ6ylemrNRIxRTOhTEdvsnPjQ=
    on_pull_requests: false
install:
- npm install
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- npm prune
- greenkeeper-lockfile-update
after_success:
- npm run coveralls
- npm run semantic-release
after_script:
- greenkeeper-lockfile-upload
